// Generated by gencpp from file ur_robot_gazebo/JointStateSimple.msg
// DO NOT EDIT!


#ifndef UR_ROBOT_GAZEBO_MESSAGE_JOINTSTATESIMPLE_H
#define UR_ROBOT_GAZEBO_MESSAGE_JOINTSTATESIMPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_robot_gazebo
{
template <class ContainerAllocator>
struct JointStateSimple_
{
  typedef JointStateSimple_<ContainerAllocator> Type;

  JointStateSimple_()
    : joint_angles()  {
    }
  JointStateSimple_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joint_angles_type;
  _joint_angles_type joint_angles;





  typedef boost::shared_ptr< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> const> ConstPtr;

}; // struct JointStateSimple_

typedef ::ur_robot_gazebo::JointStateSimple_<std::allocator<void> > JointStateSimple;

typedef boost::shared_ptr< ::ur_robot_gazebo::JointStateSimple > JointStateSimplePtr;
typedef boost::shared_ptr< ::ur_robot_gazebo::JointStateSimple const> JointStateSimpleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_robot_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ur_robot_gazebo': ['/home/abdollah/catkin_ws/src/skill_transfer/ur_robot_gazebo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11501c45f507c225d25f998a0b6418cd";
  }

  static const char* value(const ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11501c45f507c225ULL;
  static const uint64_t static_value2 = 0xd25f998a0b6418cdULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_robot_gazebo/JointStateSimple";
  }

  static const char* value(const ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_angles\n\
";
  }

  static const char* value(const ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointStateSimple_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_robot_gazebo::JointStateSimple_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_ROBOT_GAZEBO_MESSAGE_JOINTSTATESIMPLE_H
